name: seed_finder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: 3.22.2

dependencies:
  dio: ^5.4.3+1

  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.1
  table_calendar: ^3.1.2



dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.3.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10


flutter:
  uses-material-design: true
  assets:
    - .env

