// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9lreN2eFpw4y6tI7pEPCaLjlR4g3kwM',
    appId: '1:894080515848:web:6f096d050a0b1a2f5f76bd',
    messagingSenderId: '894080515848',
    projectId: 'seedfinder-23b19',
    authDomain: 'seedfinder-23b19.firebaseapp.com',
    storageBucket: 'seedfinder-23b19.appspot.com',
    measurementId: 'G-ZP1BESGX76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaDmhxNZFCguByDAd3KzHZFDJKNw731E',
    appId: '1:894080515848:android:45890f614d311b035f76bd',
    messagingSenderId: '894080515848',
    projectId: 'seedfinder-23b19',
    storageBucket: 'seedfinder-23b19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLrPPcWTC_591TySgVO8tf3Q8krqhzu8',
    appId: '1:894080515848:ios:d6a69007488e37995f76bd',
    messagingSenderId: '894080515848',
    projectId: 'seedfinder-23b19',
    storageBucket: 'seedfinder-23b19.appspot.com',
    iosBundleId: 'com.example.seedFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLrPPcWTC_591TySgVO8tf3Q8krqhzu8',
    appId: '1:894080515848:ios:d6a69007488e37995f76bd',
    messagingSenderId: '894080515848',
    projectId: 'seedfinder-23b19',
    storageBucket: 'seedfinder-23b19.appspot.com',
    iosBundleId: 'com.example.seedFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf9lreN2eFpw4y6tI7pEPCaLjlR4g3kwM',
    appId: '1:894080515848:web:b8576f666eb986a65f76bd',
    messagingSenderId: '894080515848',
    projectId: 'seedfinder-23b19',
    authDomain: 'seedfinder-23b19.firebaseapp.com',
    storageBucket: 'seedfinder-23b19.appspot.com',
    measurementId: 'G-N9LLJXT71Y',
  );
}
